server.error.include-message=always
spring.application.name=tic-tac-toe-backend

# Connection URL for postgres
# Environment variable SPRING_DATASOURCE_URL must be set in deployment
# Example: jdbc:postgresql://your-host:5432/game_sessions_storage
spring.datasource.url=${SPRING_DATASOURCE_URL}

# Credentials
# Environment variables SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD must be set
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Settings Hibernate

# Auto create-drop table on @Entity classes
spring.jpa.hibernate.ddl-auto=create-drop

# show SQL-requests to console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect databases
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect